name: Create Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
    - name: Show toolchain
      run: rustup show

    - name: Install musl toolchain
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl --bin librarian --bin server
      
    - name: Create binary tar archive
      run: tar --create --gzip --file=librarian_binaries.tar.gz target/x86_64-unknown-linux-musl/release/librarian target/x86_64-unknown-linux-musl/release/server
      
    - name: Create gzip for CLI
      run: gzip target/x86_64-unknown-linux-musl/release/librarian
        
    - uses: ncipollo/release-action@v1.12.0
      name: Generate draft release
      with:
        artifacts: librarian_binaries.tar.gz, target/x86_64-unknown-linux-musl/release/librarian.gz
        artifactErrorsFailBuild: true
        draft: true
