name: Generate Binaries

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose

    - name: Show toolchain
      run: rustup show

  Save-Binaries:

    needs: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/upload-artifact@v2
      name: Save Librarian cli
      with:
        name: librarian
        path: target/release/librarian

    - uses: actions/upload-artifact@v2
      name: Save server
      with:
        name: librarian-server
        path: target/release/server
